# Generated by Django 4.1.7 on 2023-04-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockControl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcontrol',
            name='message',
        ),
    ]
