# Generated by Django 4.1.7 on 2023-03-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=1200)),
                ('dateSingUp', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('birth', models.DateField()),
                ('ident', models.CharField(max_length=50)),
                ('accessLevel', models.IntegerField(default=3)),
            ],
        ),
    ]
