# Generated by Django 4.1.7 on 2023-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costumer',
            name='username',
            field=models.CharField(default='username', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costumer',
            name='accessLevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
