# Generated by Django 4.1.7 on 2023-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0005_remove_costumer_accesslevel_costumer_adress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='isCostumer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='isSupplier',
            field=models.BooleanField(default=False),
        ),
    ]
