# Generated by Django 4.1.7 on 2023-03-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=50)),
                ('categoria', models.CharField(default='Sin nombre', max_length=50)),
                ('shortDescription', models.CharField(default='Sin descripcion', max_length=200)),
                ('description', models.TextField(default='Sin descripcion', max_length=1200)),
                ('ean13', models.CharField(max_length=13)),
                ('ref', models.CharField(max_length=13)),
                ('stock', models.IntegerField(max_length=2000)),
                ('corridor', models.IntegerField(max_length=50)),
                ('rack', models.IntegerField(max_length=50)),
                ('supPrice', models.FloatField(max_length=10000)),
                ('pvp', models.FloatField(max_length=10000)),
                ('discount', models.FloatField(max_length=10000)),
                ('finalPrice', models.FloatField(max_length=10000)),
            ],
        ),
    ]
