# Generated by Django 4.1.7 on 2023-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='corridor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='finalPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.FloatField(verbose_name=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='rack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='supPrice',
            field=models.FloatField(),
        ),
    ]
