# Generated by Django 4.1.7 on 2023-04-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_ref_alter_product_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supPrice',
        ),
    ]
