# Generated by Django 4.1.7 on 2023-04-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_ref_remove_product_supprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minStock',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=30),
        ),
    ]
