# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_supprice_product_suplierprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='suplierPrice',
            new_name='supPrice',
        ),
    ]
