# Generated by Django 4.1.7 on 2023-03-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_suplierprice_product_supprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='corridor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ref',
        ),
    ]
