# Generated by Django 4.1.7 on 2023-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_corridor_remove_product_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean13',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finalPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pvp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shortDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supPrice',
            field=models.FloatField(null=True),
        ),
    ]
