# Generated by Django 4.1.7 on 2023-03-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_options_alter_staff_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='accessLevel',
        ),
    ]
