# Generated by Django 4.1.7 on 2023-03-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_password_staff_username_alter_staff_email'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='staff',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
