# Generated by Django 4.1.7 on 2023-03-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_password_staff_username_alter_staff_email'),
        ('supplier', '0002_supplier_password_supplier_username_and_more'),
        ('costumer', '0002_costumer_password_costumer_username_and_more'),
        ('login', '0002_login_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='costumer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='costumer.costumer'),
        ),
        migrations.AddField(
            model_name='login',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='login',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
