# Generated by Django 4.1.7 on 2023-03-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login_costumer_login_supplier_alter_login_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='accessLevel',
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
