# Generated by Django 4.1.7 on 2023-03-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_password_staff_username_alter_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='info',
        ),
    ]
