# Generated by Django 4.1.7 on 2023-03-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_options_alter_supplier_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='accessLevel',
        ),
    ]
