# Generated by Django 4.1.7 on 2023-04-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_iscostumer_supplier_issupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='adress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cif',
            field=models.CharField(default='00000000X', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='info',
            field=models.TextField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='isCostumer',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='isSupplier',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
