# Generated by Django 4.1.7 on 2023-03-28 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_sale_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 28)),
        ),
    ]
