# Generated by Django 4.1.7 on 2023-04-13 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_alter_supplier_adress_alter_supplier_cif_and_more'),
        ('product', '0012_product_supplier'),
        ('sale', '0006_suppliersale'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersale',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AlterField(
            model_name='suppliersale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
